### ISSUE TITLE
Links in buttons below walk leader's name are created incorrectly

### ISSUE THREAD

**Issue by janeswalk** [jkoudys/janeswalk-web#142] opened 2015-03-24 19:57 UTC
http://janeswalk.org/canada/calgary/stanley-park-ramsay-hidden-stairways-natural-area-trails-bridges-funky-neighbourhoods-and-cafes/

The buttons under Lori Beattie's name link to [URL for the walk]/[link] rather than [link]. I've looked at her profile and can't see what's causing this. Same thing is happening with other Calgary walks, I haven't heard yet from other cities.

**Comment by jkoudys** [comment] 2015-03-26 22:32
Duplicate of issue https://github.com/jkoudys/janeswalk-web/issues/129 , fixed Mar 22.

**Closed by jkoudys** 2015-03-26 22:32 UTC
Labels: bug, duplicate
