### ISSUE TITLE
Can both walk leaders' names appear on walk preview?

### ISSUE THREAD

**Issue by janeswalk** [jkoudys/janeswalk-web#137] opened 2015-03-22 21:24 UTC
http://janeswalk.org/canada/calgary/arts-walk/
There are 2 walk leaders -- both show at bottom under About the Walk Team -- CO would like both to show at top, next to "Walk Leader" and on walk preview card on walks list

**Comment by jkoudys** [comment] 2015-03-27 03:51
duplicate of #143

**Closed by jkoudys** 2015-03-27 03:51 UTC
Labels: duplicate, question
