### ISSUE TITLE
Clicking on "share my story" on profile page opens email link

### ISSUE THREAD

**Issue by janeswalk** [jkoudys/janeswalk-web#106] opened 2015-02-25 01:14 UTC
Should open composer directly

**Comment by monting** [comment] 2015-10-19 14:04
@jkoudys this looks like a duplicate of #151?

**Comment by jkoudys** [comment] 2015-10-19 17:21
Yes I think this can close - we're actually doing a major resdesign of the profile page, so this will need to be implemented.

**Closed by jkoudys** 2015-10-19 17:21 UTC
Labels: City 2 City
